apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: sre-platform
    app.kubernetes.io/managed-by: srectl
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  source:
    repoURL: "https://github.com/dawid-koldras-home/SRE-platform-config-local.git"
    targetRevision: "main"
    path: "platform/modules/argocd"
  destination:
    server: https://kubernetes.default.svc
    namespace: "argocd"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
